OpenStackweb/osf-website

netlify.toml, package.json, src/pages/companies/index.md, src/templates/services-page.js, static/admin/config.yml
* Navbar content is now properly displayed
* Fixed errors in Services preview page 
* Added the prop `required: false` in fields that aren't mandatory
* Pages separated and organized to make it easier to find
=> Fix CMS errors

src/components/Navbar.js, src/content/navbar.json, src/pages/four-opens/open-community/index.md, src/pages/four-opens/open-design/index.md, src/pages/four-opens/open-development/index.md, src/pages/four-opens/open-source/index.md, static/admin/config.yml
* Fix required fields in the CMS
* Allows to hide/display items from navbar through CMS configuration
=> Fix CMS fields

src/components/Navbar.js, src/content/navbar.json, src/style/modules/_about.scss, src/style/modules/_aboutstaff.scss, src/style/modules/_basestructure.scss, src/style/modules/_companies.scss, src/style/modules/_hero.scss, src/style/modules/_home.scss, src/style/modules/_nav.scss, src/style/modules/_projects.scss, static/admin/config.yml, static/admin/style/previews.css
Signed-off-by: Gabriel Horacio Cutrini <gabriel.cutrini@gmail.com>
=> Adds linking to top menu items.

src/templates/projects-page.js
Removes project list from the graphql query, since the markdown file doesn't have any pilot project
=> Provisional fix to build the site

static/admin/config.yml
Fix a typo with the latest blog changes in the cms
=> Fix config.yml file

gatsby-node.js, src/components/BlogRoll.js, src/pages/blog/index.js, src/templates/blog-post.js
* Create category pages from config file instead of reading the categories from current blog entries
* Fix routes inconsistencies between the routes generated by Gatsby and the ones used by the blog components
* Uses the url seo values as routes for blog entries instead of the automatically generated by Gatsby
=> Fix blog routing

src/components/BecomeSponsor.js, src/content/become-sponsor.json, static/admin/config.yml
* Allows to modify the content and target email for the footer banner in the companies section
=> Adding Sponsor Banner data to CMS

src/pages/404.js, src/pages/a.js, src/templates/error-page.js
* Fix style of 404 error page
* Add error page for client-side routes
=> Fix 404 page

src/components/FeaturedRoll.js, src/content/press-media.json, src/style/modules/_press.scss, src/style/style.scss, static/admin/config.yml
* Solves bug with missing articles 
* Add a simple pagination for press articles
=> Press fix pagination

src/components/AffiliationForm.js
Signed-off-by: Sebastian Marcet <smarcet@gmail.com>
=> Added new placeholder for organization field at affiliation form

src/pages/press/index.js, static/admin/config.yml
* Use the SEO data in the press file.
* CMS config to edit press SEO
=> SEO config from press file

src/components/BlogRoll.js, src/components/FeaturedRoll.js, src/components/NewsRoll.js, src/content/press-media.json, src/pages/blog/800-contributors-worldwide-deliver-23rd-openstack-release-wallaby.md, src/pages/blog/airship-2-0-arrives-delivering-support-for-public-cloud-bare-metal-with-simplified-architecture-smaller-footprint-faster-deployments.md, src/pages/blog/introducing-openinfralive-a-weekly-interactive-webinar-series.md, src/pages/blog/introducing-the-open-infrastructure-foundation-building-open-source-communities-who-write-software-to-run-in-production.md, src/pages/blog/join-us-in-building-the-next-decade-of-open-infrasrtructure.md, src/pages/blog/magma-developer-conference.md, src/pages/blog/open-infrastructure-foundation-seats-its-first-board-of-directors-including-engineers-from-ant-group-facebook-and-red-hat.md, src/pages/blog/openinfra-foundation-marketing-case-study-inmotion-hosting.md, src/pages/blog/red-hat-provides-551-9-million-in-software-subscriptions-to-boston-university-advancing-mission-of-openinfra-labs.md, src/pages/blog/remembering-dan-kohn.md, static/admin/config.yml
* Blog posts now can have multiple categories
* News and blog post set as hide from the CMS
=> News and blog posts improvements

gatsby-browser.js, gatsby-node.js, gatsby-ssr.js, src/components/Layout.js, src/components/SEO.js, src/content/navbar.json, src/pages/about/openinfra-live.md, src/pages/blog/index.js, src/pages/membership/join-the-open-infrastructure-foundation-1.md, src/state/ReduxWrapper.js, src/templates/blog-post.js, src/templates/board-page.js, src/templates/companies-page.js, src/templates/error-page.js, src/templates/generic-page.js, src/templates/hosting-page.js, src/templates/index-page.js, src/templates/join-page.js, src/templates/membership-community.js, src/templates/membership-foundation.js, src/templates/membership-resign.js, src/templates/profile-page.js, src/templates/projects-page.js, src/templates/registration-page.js, src/templates/services-page.js, src/templates/staff-page.js
* Fix issues with image OG tags
* Fix issues with links on navbar and in seo props
=> changes in SEO, OG tags, navbar links

gatsby-config.js, src/style/modules/_companies.scss, src/templates/companies-page.js
* Add rule to purge CSS to keep the new classes for company level
=> Adding company level rule to purgeCss

netlify.toml, src/content/footer-nav.json, src/content/navbar.json, src/pages/about/openinfra-partnerships.md
* updated /about/osf-partnerships to /about/openinfra-partnerships
* added redirect (301)
=> Site URL update

src/templates/openinfra-live.js
* Uses the user time in case that the API failed to fetch the timestamp
=> Openinfra Live - API catch

src/templates/openinfra-live.js
Replaced the mapping of the episode collection with the first episode of the future episode list.
=> Next episode section content blinking on refresh

src/templates/openinfra-live.js
Added a loading message when obtaining the timestamp from the api https://timeintervalsince1970.appspot.com/
=> add loading during timestamp api call

src/templates/openinfra-live.js
* Adds a catch to the API call, setting the time using the user clock
=> Add catch to API call

src/templates/members-page.js, static/admin/config.yml
* Restore the config for the CMS pointing to correct repository and branch
* Allows to use HTML content for the position field on the quote componente
=> Fix CMS config

src/templates/join-page.js, src/templates/members-page.js
* Fixing bug on previews when adding images to a list component in the CMS
=> Fixing cms previews

gatsby-config.js, package.json, yarn.lock
* Adds a gatsby plugin to implement google tag manager
=> new plugin google-tagmanager

src/components/Header.js, src/components/SEO.js, src/templates/blog-post.js, src/templates/generic-page.js
* Adds the cookie bot script on the SEO component to load it on the head tag on every page
=> Add cookie bot script to <head> on every page

src/actions/member-actions.js, src/templates/profile-page.js
ref https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=2650238
=> Fixed refresh my profile on reload

netlify.toml
=> User survey redirect

package.json, src/pages/a.js, src/routes/PrivateRoute.js, src/routes/authorization-callback-route.js, yarn.lock
* route refactoring
* added code to private route to check idtoken lifetime
ref https://tipit.avaza.com/project/view/188886#!tab=task-pane&groupby=ProjectSection&view=vertical&task=2650238&fileview=grid
=> check on idtoken lifetime

package.json, src/pages/a.js, src/routes/PrivateRoute.js, src/routes/authorization-callback-route.js, yarn.lock
* This reverts commit 6f40cc9d3023a9ac81f07d3d33bbcd6f947485a3.
=> Revert "check on idtoken lifetime (#147)"

src/routes/PrivateRoute.js
=> Fixed typo on private route refactoring

src/pages/contributors/corporate.md, src/templates/contributors-page.js
- Complete list of companies added
- Go to top button added
- CMS preview improved
=> Corporate contributors

src/content/footer-nav.json, src/content/navbar.json
Adds newsletter links to nav and footer.
=> Add newsletter links

src/templates/election-candidates-page.js, src/templates/election-gold-candidates-page.js
* Removing condition to show/hide candidate list on election pages
=> removing condition to show/hide candidate list

src/pages/four-opens/index.md, src/pages/hybrid-cloud/index.md
=> Add video links and text

src/templates/member-profile-page.js
ref https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=2753697
=> Fixed member profile page to show current candidate info

src/templates/member-profile-page.js
ref https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=2753697
=> Fixed get election profile

src/cms/cms.js, src/cms/preview-templates/ContributorsPagePreview.js, src/pages/annual-report/2021.md, src/templates/annual-report-page.js, static/admin/config.yml
=> Edit preview styles

src/cms/cms.js
=> Revert change

netlify.toml
ref
https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=2786980
=> Updated headers settings

gatsby-config.js, src/actions/summit-actions.js, src/reducers/summit-reducer.js, src/state/ReduxWrapper.js, src/style/modules/_summit.scss, src/templates/summit-sponsor-page.js
* Adding sponsos for current summit
ref: https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=2804249
=> Add Summit sponsors

src/pages/openinfra-summit/summit-sponsor.md, src/style/modules/_summit.scss, src/templates/summit-sponsor-page.js
Moved sponsor logos to top of page.
=> Sponsors page

src/style/modules/_summit.scss
=> Adjust logo margins

src/components/SummitSponsorSlider.js, src/components/SummitSponsors.js, src/style/modules/_summit.scss, src/templates/summit-page.js, src/templates/summit-sponsor-page.js
* Refactoring summit sponsors into single component.
* Adding slider of sponsors
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2804249&fileview=grid
Signed-off-by: Tomás Castillo [tcastilloboireau@gmail.com](mailto:tcastilloboireau@gmail.com)
=> Sponsor components

src/components/CompaniesSection.js, src/style/modules/_home.scss
=> Fix homepage logo sizes

src/style/modules/_summit.scss
=> Add class names and adjust sizes

src/style/modules/_subnav.scss
* Changing color to summit navbar links
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2852189
=> Change font colors in summit navbar

src/components/SummitSubNav.js
* Fixing schedule dropdown on mobile view
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2851996&fileview=grid
=> Fix mobile dropdown

src/components/SummitSubNav.js, src/style/modules/_subnav.scss
* Adding register button on mobile view at summit page 
ref: https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=2852335
=> Adding register button on summit mobile menu

package.json, src/actions/schedule-actions.js, src/components/Layout.js, src/reducers/all-schedules-reducer.js, src/reducers/schedule-reducer.js, src/state/ReduxWrapper.js, src/style/full-schedule.module.scss, src/templates/schedule-page.js, src/utils/withScheduleData.js, yarn.lock
* added reload actions
* refactored reducers
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2850915&fileview=grid
=> Added scaffolding for Schedule reducer

src/utils/alerts.js
* Adds login prompt to schedule popup
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2855178&fileview=grid
=> Adding login function to schedule login popup

gatsby-node.js, src/components/FeaturedSpeakers.js, src/style/modules/_summit.scss, src/templates/summit-page.js
* New component on summit page to display featured speakers
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2859549
=> Summit featured speakers component

src/components/RegisterNowBanner.js, src/style/style.scss, src/templates/schedule-page.js
* Adjusting mobile banner on summit schedule page
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2869031
=> Adding new registration banner for mobile

src/actions/schedule-actions.js
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2861137&fileview=grid
=> Fix share link on schedule

src/utils/schedule.js
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2878807&fileview=grid
=> Fix Abstract filter

src/utils/schedule.js
added check when filter is null
ref 
https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=2879928
=> Fixed filter level

src/components/Hosting/OurNetworkSection.js, src/components/Slideshow/index.js, src/components/Slideshow/styles.scss, src/style/modules/_hosting.scss
* calculated container width dynamically
* fixed css
* refactoring
ref https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=2927762
=> Slide Show Fix

src/components/Layout.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2979813
=> Removing navigation widget

package.json, yarn.lock
=> Fix on schedule autoscroll

src/actions/user-actions.js
* Add required calls to populate the elections and member reducers
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=3114580&fileview=grid
=> Add members and elections calls on auth callback

gatsby-node.js
moved summit id to external env variable
GATSBY_SUMMIT_ID ( defaults to current is not defined)
=> Fix on schedule not loading

src/cms/cms-utils.js, src/cms/cms.js, static/admin/admin.css
ref: https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=3186009
=> Add css file to prevent cursor jump on cms text field

src/pages/ptg/index.md, src/templates/ptg-page.js
ref https://tipit.avaza.com/project/view/188886#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3406070&stafilter=NotComplete&fileview=grid
added PTG schedule button
=> Added ptg schedule button

src/components/LazyLoadVideo/index.js, src/components/LazyLoadVideo/index.module.scss
ref: https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=3411873
=> Remove params from videoId, adjust thumbnail position

gatsby-node.js, src/templates/election-candidates-page-previous.js, src/templates/election-gold-candidates-page-previous.js
ref: https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=3400289
=> Fix issue with repeated candidates on different elections, fix profile link

src/style/modules/_election.scss, src/templates/election-candidates-page.js, src/templates/election-page-previous.js, src/templates/election-page.js
ref: https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=3418995
=> Increase font size on election alerts

gatsby-node.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3469910
=> Remove current election from past elections array

src/actions/user-actions.js, src/templates/profile-page.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3436051
=> Add expands for all_affiliations, change source for affiliations on profile

src/actions/member-actions.js, src/actions/user-actions.js, src/templates/member-profile-page.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3436051
=> Add organization expand at affiliations, change in member profile page

src/components/SponsorshipSection/SponsorshipCard/index.jsx, src/components/SponsorshipSection/SponsorshipCard/styles.scss, src/components/SponsorshipSection/index.jsx, src/components/SponsorshipSection/styles.scss, src/templates/sponsorship-page.js
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3478819&stafilter=NotComplete&fileview=grid
=> Changes for sponsorship page

src/components/SponsorshipSection/index.jsx, src/components/SponsorshipSubNav.js, src/style/modules/_subnav.scss, src/templates/sponsorship-page.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3510167
=> Add anchor tags and subnav bar on sponsorship pages

src/components/SponsorshipSubNav.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3510167
=> Remove sponsorship link on subnavbar

src/pages/ptg/index.md
Shortened description at top of page.
=> Update PTG description

src/components/ImageOnlyHeader.js, src/style/modules/_image-only-header.scss, src/style/modules/_join.scss
ref: https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=3560037
=> Fix mobile view on join page, fix headerv2 mobile

src/components/SponsorshipSection/index.jsx, src/components/SponsorshipSection/styles.scss, src/templates/sponsorship-page.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3570926
=> Add link on sponsorships and link it to blog post

src/components/UpcomingSummits/index.jsx
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3572858
=> Update notification message on summit page

src/components/AffiliationForm.js, src/reducers/user-reducer.js, src/style/modules/_affiliations.scss, src/templates/profile-page.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3636353
=> fix: adjust timezone issue on datepicker, fix props for current affiliations

gatsby-node.js
ref: https://tipit.avaza.com/project/view#!tab=task-pane&task=3660967
=> fix: remove files that doesn't have election data

gatsby-node.js, src/components/BlogRoll.js, src/utils/methods.js
ref: https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=3726262
=> fix: use urijs to clean domain and generate path for pages

src/pages/ptg/index.md, src/style/modules/_ptg.scss, src/templates/ptg-page.js
ref: https://tipit.avaza.com/project/view#!tab=task-pane&task=3748937
=> Add team list for ptg 2025

src/components/SponsorshipSection/SponsorshipCard/index.jsx, src/components/SponsorshipSection/SponsorshipCard/styles.scss, src/components/SponsorshipSection/index.jsx, src/templates/sponsorship-page.js
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3782013&stafilter=NotComplete&fileview=grid
=> update sponsorships page

src/components/MembershipType.js, src/components/ProfileManagementComponent.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3828566
=> fix: adjust profile links and changes in membership

src/templates/summit-landing-page.js
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3800009&stafilter=NotComplete&fileview=grid
=> Fix: update copy on summit travel section

src/actions/election-actions.js, src/actions/event-actions.js, src/actions/user-actions.js, src/utils/security.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3824698
=> fix: update getAccessTokenSafely, include logout and reject method

src/components/MembershipType.js, src/components/ProfileManagementComponent.js, src/routes/PrivateRoute.js, src/style/modules/_membership-type.scss, src/templates/join-individual-page.js, src/templates/registration-page.js, src/utils/security.js
change buttons and interactions to have in consideration new OIF individual membership
ref https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=3832805
=> fix: update profile page

src/pages/ptg/index.md
Add reg button back
Add team signup button back
=> Update PTG Site for October 2025 PTG
